### ISSUE TITLE
CIGAR string bug when clipping due to end of scaffold

### ISSUE THREAD

**Issue by GenomeRIK** [ydLiu-HIT/deSALT#19]
Hello,

I am reporting an issue in deSALT which was brought to my attention by someone using deSALT with TAMA. 

The issue seems to be that when a read is mapped near the end of a scaffold and the end of the read extends beyond the scaffold, the CIGAR string has 1 extra base position in the last exon.

This is the line in the BAM file where the issue occurred:
68:2191|8a1e69dc-0e1c-4abd-8fca-8f5eb6039001 0 scaffold_102 83929 60 2S295M57N292M56N423M61N103M50N678M2D163M176S * 0 0 GAAAAGGTTGTTCCTCAACCGCCATCATCAACATCCTACAGGGCCCCTCAAGGCTTATTTTCAATGTCTGATTACCGCTAGCTACAGGTCGCCAACAACGAGCTGCGCAGCTTATACCCACAAACACAAGGCAGCGCTTGAGAAACCCCTGCATCTATACCAGCGTTGCAAAGGGATGGTCGCGGCTCTTCTGCCAGTTATTTCGCCTCTGGGGACAAGATGAGGGTGTTTCTTCAAGAATCCCCCTTTCCAGGCTTTGTTTGAGCTTCGAAGAAAGGCGGGCAAGGTCGTGAATCGGCAATCTGCCTACTTCTCAGAAGACCTGTGGACGTTGTGAACACCCGAACCGCGCTGTCTGCAAGAGGCCTTGGTACATACACGCCCCCTTCGTGATATATCTTCGAGAACCAGACCGGGTCGCAGCCAGTCTCGTGAACCAGACGGGAGAACGATTATCTTGTCCAATGAATCGAGTCTTTGTTCGCGAGGATAAACTCATGGCCAGGCACCAGACAGGCCATCGTACTCGACTCCTAACAGAGTTTTTACGCCGTGTCTCTAGACAGTAGCTTCGTAGAAGCGTTTCGAGAACCTCGCTGTACTTACTTCAAAGGAATAACTTGGATCAGGATGAATGTAGCAACTTCAGAAGTTCCAATGGACCCCAGTAAACCGATTCCTCTCGGTTCTCGCAAGCAAGTTATCAGCGTGCCTAAACCGCACCGGTTGGCGAAATTCCATCTGACTTCTTACGGATATCTGGTCGCGCACTACCGTATAGGAATAGCTGATTGATCACCTGGTCGCACCAAAGCACGCCAAAACCCGTTGGAAAACCGGATGGTTTCACCCTGAACGAGAAAGCATCTGGGAAGCGCGAATGCTGAACCAGTACGTGGTGTCCTCAAGTACATTCCCTCTTGGCTCCTGGAGCCGGGTGGCAAGAGTATCTTCGGCGATGCGCAGAGATCACTTCGTATTCTCTCGAGATAGGCCTTTCAATGATGCGATGACGAAAGGAACCACTTTCCTGCCGGACCCCTGGTAAGGGCGTCGACATTCATGAGGGCGGCGGGCTTCGATCCAGACGTCGCTGCATTTGGCTGTGGTCGTCGACGATTGGCCCAGGCCGACATCTAAGCCACGACTCGCTCCTCTACATGACTGCGTCCCGCCTATCCATCTTCAACGCACGCGAAGAGCAAGGAGGGAAACCCTTGAAACTAGAGATCACCTCGGCGCTGATGCCATAAGTGCGGTTCTTCCGTTCTCACTTTCCGCTCTAAACGAAAGGGACGATCCTGATGCCTCGCTGAAAATGGGATGTAGGAAATTTGTCCCGTTCAAATGCGAGATCGTGCCTCGTTCGGGAGGCATGCTGCTTTAATTCGGTCATTGGGGTAATAACTTGGCAGTTCATTTCAACCGGTGACCTACCTTTCTTTCTGTCTAGAAGTTCTGAAGGTGTGCAAAGTACGTACAGCAACACCGAGTAAACGGCCCTGAAAGATGGAACGTGCATTTGTGTACCTCCGACTCCACTCCTCCAAATAAGCGCCGACTTCTGAATGCCCGCCAGTGGAGAGTATCAGATGGCAGCGCGAATGGACACCCGTCCAGACCACCGCCAAGAGGACCCCCCAAAATCTCGACGAAGGTCCGAGCGGATTCCGGACAGGATTTTCAGGTTTTGGGGACAGGCTGGAGGTCAAATCCGGACAGAAAAGGGAATTTTGAGGCCGCAAGGCCAGTGAAATCCCGGACAAAATTGGCATTTTTGGCCTCAACGGCGGAAAAAAAACGCCAATTTGCGAAACGAGCGCCGCACCCGGACATTTTTTGCGGTTTCTGAGGCGCGAGGCCTGATAAACGCCCGGACAGGAACTCCAAATTCGAGATTTTTGCTCCGGACGGGAGACCGGGAACCTGTATCGGGCCTTTATCGAGGTATTGGGGGGTCCTCCGCCAAGGGCCTCCTGCATGCCAACGAGGCGCGAGACCAACGTCATCGAAGCCCAAACGTTTCATCTCGTTTGGACCCCAGTTTCCCGGTAAGCCTAGTCGGACACCCAGAGCCCAAATTTCGCGCTCAAAACGGAAGACCAAGAGTATTATTTTTTGCGTAAAAGAAA * NM:i:2 ms:i:1946 AS:i:1944nn:i:0

The last 163 bases in the scaffold are:
AAAAAAAAACGCCAATTTGCGAAACGAGCGCCGCACCCGGACATTTTTTGCGGTTTCTGAGGCGCGAGGCCTGATAAACGCCCGGACAGGAACTCCAAATTCGAGATTTTTGCTCCGGACGGGAGACCGGGAACCTGTATCGGGCCTTTATCGAGGTATTGGG

And the CIGAR string says that the last exon is 163 bases:
163M176S

However, you can see that the read only has 162 bases mapping for the last exon:
"G [splice junction] AAAAAAAACGCCAATTTGCGAAACGAGCGCCGCACCCGGACATTTTTTGCGGTTTCTGAGGCGCGAGGCCTGATAAACGCCCGGACAGGAACTCCAAATTCGAGATTTTTGCTCCGGACGGGAGACCGGGAACCTGTATCGGGCCTTTATCGAGGTATTGGG [end of mapping]"

This issue was detected when the user tried to run TAMA Collapse using the deSALT bam file. TAMA Collapse reported that the genome sequence length for that exon did not match the read sequence length. 

I have asked the user to send me the scaffold sequence so you can recreate the issue and debug. I will send the scaffold sequence to when I have received it. 

However, you should be able to recreate the bug by making a fake read with the same sequence as the end of a scaffold and then extending the sequence for a few hundred bases. If you map this read onto the scaffold, it should show the same issue with the CIGAR string representation. 

Thank you,
Richard

**Comment by GenomeRIK** [comment]
Hello,

The user has supplied the data for debugging this:

[Botond_scaffold_102.zip](https://github.com/ydLiu-HIT/deSALT/files/4220576/Botond_scaffold_102.zip)

Also you can find the issue thread on the TAMA repo where this bug came to light:
https://github.com/GenomeRIK/tama/issues/19

Thank you,
Richard

**Comment by ydLiu-HIT** [comment]
Hi, 
Thanks for reporting the issue.

Based on the given scaffold and reads, I create the index with "deSALT index Copci_scaffold_102.fasta ./index" and align the reads with the command "deSALT aln -t 1 -I 1000 -l 14 -s 2 -x ccs -O6,24 -M4 -o ./aln.sam index/ nanopore_reads_from_scaffold_102_edge.fa". But I got the following SAM line:

68:2191|8a1e69dc-0e1c-4abd-8fca-8f5eb6039001    0       scaffold_102    83929   60      2S295M57N292M56N423M61N103M50N678M2D162M177S
    *       0       0       GAAAAGGTTGTTCCTCAACCGCCATCATCAACATCCTACAGGGCCCCTCAAGGCTTATTTTCAATGTCTGATTACCGCTAGCTACAGGTCGCCAACAACGAGCTGCGCAGCTTATACCCACAAACACAAGGCAGCGCTTGAGAAACCCCTGCATCTATACCAGCGTTGCAAAGGGATGGTCGCGGCTCTTCTGCCAGTTATTTCGCCTCTGGGGACAAGATGAGGGTGTTTCTTCAAGAATCCCCCTTTCCAGGCTTTGTTTGAGCTTCGAAGAAAGGCGGGCAAGGTCGTGAATCGGCAATCTGCCTACTTCTCAGAAGACCTGTGGACGTTGTGAACACCCGAACCGCGCTGTCTGCAAGAGGCCTTGGTACATACACGCCCCCTTCGTGATATATCTTCGAGAACCAGACCGGGTCGCAGCCAGTCTCGTGAACCAGACGGGAGAACGATTATCTTGTCCAATGAATCGAGTCTTTGTTCGCGAGGATAAACTCATGGCCAGGCACCAGACAGGCCATCGTACTCGACTCCTAACAGAGTTTTTACGCCGTGTCTCTAGACAGTAGCTTCGTAGAAGCGTTTCGAGAACCTCGCTGTACTTACTTCAAAGGAATAACTTGGATCAGGATGAATGTAGCAACTTCAGAAGTTCCAATGGACCCCAGTAAACCGATTCCTCTCGGTTCTCGCAAGCAAGTTATCAGCGTGCCTAAACCGCACCGGTTGGCGAAATTCCATCTGACTTCTTACGGATATCTGGTCGCGCACTACCGTATAGGAATAGCTGATTGATCACCTGGTCGCACCAAAGCACGCCAAAACCCGTTGGAAAACCGGATGGTTTCACCCTGAACGAGAAAGCATCTGGGAAGCGCGAATGCTGAACCAGTACGTGGTGTCCTCAAGTACATTCCCTCTTGGCTCCTGGAGCCGGGTGGCAAGAGTATCTTCGGCGATGCGCAGAGATCACTTCGTATTCTCTCGAGATAGGCCTTTCAATGATGCGATGACGAAAGGAACCACTTTCCTGCCGGACCCCTGGTAAGGGCGTCGACATTCATGAGGGCGGCGGGCTTCGATCCAGACGTCGCTGCATTTGGCTGTGGTCGTCGACGATTGGCCCAGGCCGACATCTAAGCCACGACTCGCTCCTCTACATGACTGCGTCCCGCCTATCCATCTTCAACGCACGCGAAGAGCAAGGAGGGAAACCCTTGAAACTAGAGATCACCTCGGCGCTGATGCCATAAGTGCGGTTCTTCCGTTCTCACTTTCCGCTCTAAACGAAAGGGACGATCCTGATGCCTCGCTGAAAATGGGATGTAGGAAATTTGTCCCGTTCAAATGCGAGATCGTGCCTCGTTCGGGAGGCATGCTGCTTTAATTCGGTCATTGGGGTAATAACTTGGCAGTTCATTTCAACCGGTGACCTACCTTTCTTTCTGTCTAGAAGTTCTGAAGGTGTGCAAAGTACGTACAGCAACACCGAGTAAACGGCCCTGAAAGATGGAACGTGCATTTGTGTACCTCCGACTCCACTCCTCCAAATAAGCGCCGACTTCTGAATGCCCGCCAGTGGAGAGTATCAGATGGCAGCGCGAATGGACACCCGTCCAGACCACCGCCAAGAGGACCCCCCAAAATCTCGACGAAGGTCCGAGCGGATTCCGGACAGGATTTTCAGGTTTTGGGGACAGGCTGGAGGTCAAATCCGGACAGAAAAGGGAATTTTGAGGCCGCAAGGCCAGTGAAATCCCGGACAAAATTGGCATTTTTGGCCTCAACGGCGGAAAAAAAACGCCAATTTGCGAAACGAGCGCCGCACCCGGACATTTTTTGCGGTTTCTGAGGCGCGAGGCCTGATAAACGCCCGGACAGGAACTCCAAATTCGAGATTTTTGCTCCGGACGGGAGACCGGGAACCTGTATCGGGCCTTTATCGAGGTATTGGGGGGTCCTCCGCCAAGGGCCTCCTGCATGCCAACGAGGCGCGAGACCAACGTCATCGAAGCCCAAACGTTTCATCTCGTTTGGACCCCAGTTTCCCGGTAAGCCTAGTCGGACACCCAGAGCCCAAATTTCGCGCTCAAAACGGAAGACCAAGAGTATTATTTTTTGCGTAAAAGAAA    *       NM:i:2  ms:i:1945       AS:i:1945       nn:i:0

There have differences with your report. At the end of the reads, there have 162 matches and 177 clips.
The version of deSALT I use was v1.5.2 from bioconda. So I have no idea where is the question comes from? Maybe there have only one scaffold, the reads have no more bases to extend. Thus, if you can support other more scaffolds near the current scaffold, the question will come out.

Best.

**Comment by HegedusB** [comment]
Hia Liu,
I like to combine your deSALT aligner (because it can handle short exons really well) and the tama package (because it can collapse the aligned reads into transcripts quite accurately).

I am using the deSALT v1.5.2 from bioconda installed into a clean Ubuntu linux 18.04.3LTS docker container.  I created the alignment with these commands:
1. deSALT index ref_genome.fasta refgen_index/
2. deSALT aln -t 40 -I 1000 -a 6 -k 22 -l 14 -s 2 -x ccs -O6,24 -M4 -o ./all_ONT_reads_desalt_aln_a6k22l14s2.sam ./refgen_index ../reads/all_ONT_reads.fasta

I will repeat the alignment and check if the result is the same. In this point I just can not figure out what went wrong in the previous run.

Thanks both of you help!

**Comment by HegedusB** [comment]
I have repeated the mapping and I have got an interesting result. If I am using all of my reads I get this result , which is bad:
68:2191|8a1e69dc-0e1c-4abd-8fca-8f5eb6039001    0       scaffold_102    83929   60      2S295M57N292M56N423M61N103M50N678M2D163M176S    *       0       0       gaAAAGGTTGTTCCTCAACCGCCATCATCAACATCCTACAGGGCCCCTCAAGGCTTATTTTCAATGTCTGATTACCGCTAGCTACAGGTCGCCAACAACGAGCTGCGCAGCTTATACCCACAAACACAAGGCAGCGCTTGAGAAACCCCTGCATCTATACCAGCGTTGCAAAGGGATGGTCGCGGCTCTTCTGCCAGTTATTTCGCCTCTGGGGACAAGATGAGGGTGTTTCTTCAAGAATCCCCCTTTCCAGGCTTTGTTTGAGCTTCGAAGAAAGGCGGGCAAGGTCGTGAATCGGCAATCTGCCTACTTCTCAGAAGACCTGTGGACGTTGTGAACACCCGAACCGCGCTGTCTGCAAGAGGCCTTGGTACATACACGCCCCCTTCGTGATATATCTTCGAGAACCAGACCGGGTCGCAGCCAGTCTCGTGAACCAGACGGGAGAACGATTATCTTGTCCAATGAATCGAGTCTTTGTTCGCGAGGATAAACTCATGGCCAGGCACCAGACAGGCCATCGTACTCGACTCCTAACAGAGTTTTTACGCCGTGTCTCTAGACAGTAGCTTCGTAGAAGCGTTTCGAGAACCTCGCTGTACTTACTTCAAAGGAATAACTTGGATCAGGATGAATGTAGCAACTTCAGAAGTTCCAATGGACCCCAGTAAACCGATTCCTCTCGGTTCTCGCAAGCAAGTTATCAGCGTGCCTAAACCGCACCGGTTGGCGAAATTCCATCTGACTTCTTACGGATATCTGGTCGCGCACTACCGTATAGGAATAGCTGATTGATCACCTGGTCGCACCAAAGCACGCCAAAACCCGTTGGAAAACCGGATGGTTTCACCCTGAACGAGAAAGCATCTGGGAAGCGCGAATGCTGAACCAGTACGTGGTGTCCTCAAGTACATTCCCTCTTGGCTCCTGGAGCCGGGTGGCAAGAGTATCTTCGGCGATGCGCAGAGATCACTTCGTATTCTCTCGAGATAGGCCTTTCAATGATGCGATGACGAAAGGAACCACTTTCCTGCCGGACCCCTGGTAAGGGCGTCGACATTCATGAGGGCGGCGGGCTTCGATCCAGACGTCGCTGCATTTGGCTGTGGTCGTCGACGATTGGCCCAGGCCGACATCTAAGCCACGACTCGCTCCTCTACATGACTGCGTCCCGCCTATCCATCTTCAACGCACGCGAAGAGCAAGGAGGGAAACCCTTGAAACTAGAGATCACCTCGGCGCTGATGCCATAAGTGCGGTTCTTCCGTTCTCACTTTCCGCTCTAAACGAAAGGGACGATCCTGATGCCTCGCTGAAAATGGGATGTAGGAAATTTGTCCCGTTCAAATGCGAGATCGTGCCTCGTTCGGGAGGCATGCTGCTTTAATTCGGTCATTGGGGTAATAACTTGGCAGTTCATTTCAACCGGTGACCTACCTTTCTTTCTGTCTAGAAGTTCTGAAGGTGTGCAAAGTACGTACAGCAACACCGAGTAAACGGCCCTGAAAGATGGAACGTGCATTTGTGTACCTCCGACTCCACTCCTCCAAATAAGCGCCGACTTCTGAATGCCCGCCAGTGGAGAGTATCAGATGGCAGCGCGAATGGACACCCGTCCAGACCACCGCCAAGAGGACCCCCCAAAATCTCGACGAAGGTCCGAGCGGATTCCGGACAGGATTTTCAGGTTTTGGGGACAGGCTGGAGGTCAAATCCGGACAGAAAAGGGAATTTTGAGGCCGCAAGGCCAGTGAAATCCCGGACAAAATTGGCATTTTTGGCCTCAACGGCGGAAAAAAAACGCCAATTTGCGAAACGAGCGCCGCACCCGGACATTTTTTGCGGTTTCTGAGGCGCGAGGCCTGATAAACGCCCGGACAGGAACTCCAAATTCGAGATTTTTGCTCCGGACGGGAGACCGGGAACCTGTATCGGGCCTTTATCGAGGTATTGGGGGGTCCTCCGCCAAGGGCCTCCTGCATGCCAACGAGGCGCGAGACCAACGTCATCGAAGCCCAAACGTTTCATCTCGTTTGGACCCCAGTTTCCCGGtaagcctagtcggacacccagagcccaaatttcgcgctcaaaacggaagaccaagagtattattttttgcgtaaaagaaa        *       NM:i:2  ms:i:1946       AS:i:1944       nn:i:0

If I am using sub sampled nanopore_reads_from_scaffold_102_edge.fa reads I get this result, which is good:
68:2191|8a1e69dc-0e1c-4abd-8fca-8f5eb6039001    0       scaffold_102    83929   60      2S295M57N292M56N423M61N103M50N678M2D162M177S    *       0       0       GAAAAGGTTGTTCCTCAACCGCCATCATCAACATCC
TACAGGGCCCCTCAAGGCTTATTTTCAATGTCTGATTACCGCTAGCTACAGGTCGCCAACAACGAGCTGCGCAGCTTATACCCACAAACACAAGGCAGCGCTTGAGAAACCCCTGCATCTATACCAGCGTTGCAAAGGGATGGTCGCGGCTCTTCTGCCAGTTATTTCGCCTCTGGGGACAAGATGAGGGTGTTTC
TTCAAGAATCCCCCTTTCCAGGCTTTGTTTGAGCTTCGAAGAAAGGCGGGCAAGGTCGTGAATCGGCAATCTGCCTACTTCTCAGAAGACCTGTGGACGTTGTGAACACCCGAACCGCGCTGTCTGCAAGAGGCCTTGGTACATACACGCCCCCTTCGTGATATATCTTCGAGAACCAGACCGGGTCGCAGCCAGT
CTCGTGAACCAGACGGGAGAACGATTATCTTGTCCAATGAATCGAGTCTTTGTTCGCGAGGATAAACTCATGGCCAGGCACCAGACAGGCCATCGTACTCGACTCCTAACAGAGTTTTTACGCCGTGTCTCTAGACAGTAGCTTCGTAGAAGCGTTTCGAGAACCTCGCTGTACTTACTTCAAAGGAATAACTTGG
ATCAGGATGAATGTAGCAACTTCAGAAGTTCCAATGGACCCCAGTAAACCGATTCCTCTCGGTTCTCGCAAGCAAGTTATCAGCGTGCCTAAACCGCACCGGTTGGCGAAATTCCATCTGACTTCTTACGGATATCTGGTCGCGCACTACCGTATAGGAATAGCTGATTGATCACCTGGTCGCACCAAAGCACGCC
AAAACCCGTTGGAAAACCGGATGGTTTCACCCTGAACGAGAAAGCATCTGGGAAGCGCGAATGCTGAACCAGTACGTGGTGTCCTCAAGTACATTCCCTCTTGGCTCCTGGAGCCGGGTGGCAAGAGTATCTTCGGCGATGCGCAGAGATCACTTCGTATTCTCTCGAGATAGGCCTTTCAATGATGCGATGACGA
AAGGAACCACTTTCCTGCCGGACCCCTGGTAAGGGCGTCGACATTCATGAGGGCGGCGGGCTTCGATCCAGACGTCGCTGCATTTGGCTGTGGTCGTCGACGATTGGCCCAGGCCGACATCTAAGCCACGACTCGCTCCTCTACATGACTGCGTCCCGCCTATCCATCTTCAACGCACGCGAAGAGCAAGGAGGGA
AACCCTTGAAACTAGAGATCACCTCGGCGCTGATGCCATAAGTGCGGTTCTTCCGTTCTCACTTTCCGCTCTAAACGAAAGGGACGATCCTGATGCCTCGCTGAAAATGGGATGTAGGAAATTTGTCCCGTTCAAATGCGAGATCGTGCCTCGTTCGGGAGGCATGCTGCTTTAATTCGGTCATTGGGGTAATAAC
TTGGCAGTTCATTTCAACCGGTGACCTACCTTTCTTTCTGTCTAGAAGTTCTGAAGGTGTGCAAAGTACGTACAGCAACACCGAGTAAACGGCCCTGAAAGATGGAACGTGCATTTGTGTACCTCCGACTCCACTCCTCCAAATAAGCGCCGACTTCTGAATGCCCGCCAGTGGAGAGTATCAGATGGCAGCGCGA
ATGGACACCCGTCCAGACCACCGCCAAGAGGACCCCCCAAAATCTCGACGAAGGTCCGAGCGGATTCCGGACAGGATTTTCAGGTTTTGGGGACAGGCTGGAGGTCAAATCCGGACAGAAAAGGGAATTTTGAGGCCGCAAGGCCAGTGAAATCCCGGACAAAATTGGCATTTTTGGCCTCAACGGCGGAAAAAAA
ACGCCAATTTGCGAAACGAGCGCCGCACCCGGACATTTTTTGCGGTTTCTGAGGCGCGAGGCCTGATAAACGCCCGGACAGGAACTCCAAATTCGAGATTTTTGCTCCGGACGGGAGACCGGGAACCTGTATCGGGCCTTTATCGAGGTATTGGGGGGTCCTCCGCCAAGGGCCTCCTGCATGCCAACGAGGCGCG
AGACCAACGTCATCGAAGCCCAAACGTTTCATCTCGTTTGGACCCCAGTTTCCCGGTAAGCCTAGTCGGACACCCAGAGCCCAAATTTCGCGCTCAAAACGGAAGACCAAGAGTATTATTTTTTGCGTAAAAGAAA        *       NM:i:2  ms:i:1945       AS:i:1945       nn:i
:0

Now I am totally confused!

**Comment by ydLiu-HIT** [comment]
Do you align to the same index when you run sub-sampled nanopore_reads_from_scaffold_102_edge.fa compare to usingall reads？

**Comment by HegedusB** [comment]
No. I created a new one. Replicated your commands (deSALT index Copci_scaffold_102.fasta ./index)

**Comment by ydLiu-HIT** [comment]
I think two reasons may cause error cigars.
1. there has only one scaffold(scaffold-102), the reads have no more bases to extend at the boundary, so the CIGAR was ok.
2. deSALT use a 2-pass strategy to generate alignment skeletons and refine exons(especially for high-error reads and short exons), so only part of reads can't get complete results compare to using all reads.

So can you try to align the sub-sampled reads to the entire index used for all reads? Then show me the alignment CIGAR of the issue read to help me fix the error.
Thanks.

**Comment by HegedusB** [comment]
Ok. I repeated the mapping with the asked indexes.
Here is the result:
68:2191|8a1e69dc-0e1c-4abd-8fca-8f5eb6039001    0       scaffold_102    83929   60      2S295M57N292M56N423M61N103M50N678M2D163M176S    *       0       0       GAAAAGGTTGTTCCTCAACCGCCATCATCAACATC$
TACAGGGCCCCTCAAGGCTTATTTTCAATGTCTGATTACCGCTAGCTACAGGTCGCCAACAACGAGCTGCGCAGCTTATACCCACAAACACAAGGCAGCGCTTGAGAAACCCCTGCATCTATACCAGCGTTGCAAAGGGATGGTCGCGGCTCTTCTGCCAGTTATTTCGCCTCTGGGGACAAGATGAGGGTGTTT$
TTCAAGAATCCCCCTTTCCAGGCTTTGTTTGAGCTTCGAAGAAAGGCGGGCAAGGTCGTGAATCGGCAATCTGCCTACTTCTCAGAAGACCTGTGGACGTTGTGAACACCCGAACCGCGCTGTCTGCAAGAGGCCTTGGTACATACACGCCCCCTTCGTGATATATCTTCGAGAACCAGACCGGGTCGCAGCCAG$
CTCGTGAACCAGACGGGAGAACGATTATCTTGTCCAATGAATCGAGTCTTTGTTCGCGAGGATAAACTCATGGCCAGGCACCAGACAGGCCATCGTACTCGACTCCTAACAGAGTTTTTACGCCGTGTCTCTAGACAGTAGCTTCGTAGAAGCGTTTCGAGAACCTCGCTGTACTTACTTCAAAGGAATAACTTGG
ATCAGGATGAATGTAGCAACTTCAGAAGTTCCAATGGACCCCAGTAAACCGATTCCTCTCGGTTCTCGCAAGCAAGTTATCAGCGTGCCTAAACCGCACCGGTTGGCGAAATTCCATCTGACTTCTTACGGATATCTGGTCGCGCACTACCGTATAGGAATAGCTGATTGATCACCTGGTCGCACCAAAGCACGCC
AAAACCCGTTGGAAAACCGGATGGTTTCACCCTGAACGAGAAAGCATCTGGGAAGCGCGAATGCTGAACCAGTACGTGGTGTCCTCAAGTACATTCCCTCTTGGCTCCTGGAGCCGGGTGGCAAGAGTATCTTCGGCGATGCGCAGAGATCACTTCGTATTCTCTCGAGATAGGCCTTTCAATGATGCGATGACGA
AAGGAACCACTTTCCTGCCGGACCCCTGGTAAGGGCGTCGACATTCATGAGGGCGGCGGGCTTCGATCCAGACGTCGCTGCATTTGGCTGTGGTCGTCGACGATTGGCCCAGGCCGACATCTAAGCCACGACTCGCTCCTCTACATGACTGCGTCCCGCCTATCCATCTTCAACGCACGCGAAGAGCAAGGAGGG$
AACCCTTGAAACTAGAGATCACCTCGGCGCTGATGCCATAAGTGCGGTTCTTCCGTTCTCACTTTCCGCTCTAAACGAAAGGGACGATCCTGATGCCTCGCTGAAAATGGGATGTAGGAAATTTGTCCCGTTCAAATGCGAGATCGTGCCTCGTTCGGGAGGCATGCTGCTTTAATTCGGTCATTGGGGTAATAA$
TTGGCAGTTCATTTCAACCGGTGACCTACCTTTCTTTCTGTCTAGAAGTTCTGAAGGTGTGCAAAGTACGTACAGCAACACCGAGTAAACGGCCCTGAAAGATGGAACGTGCATTTGTGTACCTCCGACTCCACTCCTCCAAATAAGCGCCGACTTCTGAATGCCCGCCAGTGGAGAGTATCAGATGGCAGCGCG$
ATGGACACCCGTCCAGACCACCGCCAAGAGGACCCCCCAAAATCTCGACGAAGGTCCGAGCGGATTCCGGACAGGATTTTCAGGTTTTGGGGACAGGCTGGAGGTCAAATCCGGACAGAAAAGGGAATTTTGAGGCCGCAAGGCCAGTGAAATCCCGGACAAAATTGGCATTTTTGGCCTCAACGGCGGAAAAAA$
ACGCCAATTTGCGAAACGAGCGCCGCACCCGGACATTTTTTGCGGTTTCTGAGGCGCGAGGCCTGATAAACGCCCGGACAGGAACTCCAAATTCGAGATTTTTGCTCCGGACGGGAGACCGGGAACCTGTATCGGGCCTTTATCGAGGTATTGGGGGGTCCTCCGCCAAGGGCCTCCTGCATGCCAACGAGGCGC$
AGACCAACGTCATCGAAGCCCAAACGTTTCATCTCGTTTGGACCCCAGTTTCCCGGTAAGCCTAGTCGGACACCCAGAGCCCAAATTTCGCGCTCAAAACGGAAGACCAAGAGTATTATTTTTTGCGTAAAAGAAA        *       NM:i:2  ms:i:1946       AS:i:1946       nn:$
:0

**Comment by ydLiu-HIT** [comment]
Ok, thanks.
I think the issue was caused by the boundary over the scaffold length. Could you share with me the reference genome or the website link which I can download myself in order to solve this error?

Best.

**Comment by HegedusB** [comment]
Thanks a lot. 
I think it will be easier if I just upload hear.

[Reference_genome.zip](https://github.com/ydLiu-HIT/deSALT/files/4230585/Reference_genome.zip)

**Comment by ydLiu-HIT** [comment]
Hi,
I have changed the details of the scaffold boundary.  The new version is upload at the bottom. There have no CIGAR errors for your support sub-sampled reads. But I'm not sure there have other questions, so I hope you can report to me after you test on your whole nanopore reads. If your report was ok, I will upload the new version to the release page and bioconda.

Thanks a lot for helping me fix this error.
Best,
Yadong.

[deSALT-v1.5.3.zip](https://github.com/ydLiu-HIT/deSALT/files/4233921/deSALT-v1.5.3.zip)

**Comment by HegedusB** [comment]
Hi,
I have tried out the new version. The good news is the previously indicated "mapped reads with zero coordinate" issue do not appear again and the CIGAR string looks okay with that particular read. The bad news is that the tama program and the deSALT mapper still do not work together properly. I have got in the tama a similar error message but now in a different location. So I have to check which programs is responsible for the issue. When I figure out I will let you know.

**Comment by GenomeRIK** [comment]
Hi Yadong,

HegedusB has logged the new error output on the TAMA issue thread .

The new error in TAMA is the same type as the original error posted but the BAM line that triggered the error is showing something even weirder. 

This is the bam line:
66:354|771937c0-05dc-46eb-8001-426b56fc5069 0 scaffold_114 78583 60 119S152M * 0 0 GTGGGTTACCAACTGTTAGTCGCAGGCGGCTGTTCTTCATCTACACTGTTCTTCTTCCCGACGCCACGCAAGGCGCCTTTGCGCGTGAGAACGGAGCGAAGGCGCTGGAGGGACGTGCGCGGTCCTGCAGATGGAGGGGGCTCGGCTCTGTCAGGGACGGCATAGCTCTTCCTCCACCATTCCGAGAGTGTCCCTTTCTCCCCCTTGGAATCTCCTACCATCCACCAGTTTCGTTTCTCTGTCGTTTGGGCCTCGACATCCTTTGGATTCT * NM:i:1 ms:i:147 AS:i:147 nn:i:0

Apparently scaffold_114 is only 78582 bp long.

So this BAM line is showing that the alignment begins at a coordinate which is not even within the scaffold. 

On top of that, the CIGAR string suggests that the first 119 bp of the read were soft clipped and the bases align right after the scaffold ends. 

So again there seems to be some issue with how deSALT is handling alignments at the end of scaffolds. 

Thank you,
Richard

**Comment by ydLiu-HIT** [comment]
Thanks a lot. 
This issue comes out when I add some codes to solve the previous error, the revised deSALT code can address the previous CIGAR error, but I have no enough reads to test the code if there are other errors. From your description, I know why the new error comes out roughly.
So I will solve the error as soon as possible.

Thanks both of you help!

**Comment by ydLiu-HIT** [comment]
Hi, Richard and Botond

I have addressed the error and attach the newly revised codes. If there have any other questions, let me know.
Good luck！
Yadong

[deSALT-v1.5.3.zip](https://github.com/ydLiu-HIT/deSALT/files/4236784/deSALT-v1.5.3.zip)

**Comment by HegedusB** [comment]
Hi Liu,
The problems with the reads mapped to the scaffolds end still exists.
Now the problem appeared with this read:

76:1172|992467c3-d94a-4021-a45c-a0ccb6f26176    16      scaffold_131    71037   60      10S16M8D680N8D1M866I205M5S      *       0       0       CTGACTGGAACTACCATCAGCGCATGTAGAAATGCAACATCATCTGTTCAAGCACAACACTAAAAAATGCTGGGTGTTGATAAGGACGCAATAAGCTGAGTTCAGGGGATGGGGCAAACCTGCCACGCTTCCCACGATGCGGCAGAAGGCACTGCTGAGGACCGTGATGCGCTCGGCCTTCCCAGACCCCAGCACAGAAGTCTAGTGGTAGTAACGTCAGGGCATACGAAGCAGGGAGCTTGGAAGAGGATGAAGAGGCTGGATGCTGGAGGATGAGGATGACAATGAAGAAGGCGATGATGGCGAAAACGAAGACGGCAATGCTTGAAAGCGGCAATGAGATGAAACGAAAGATGATGAGATGAGAAGTAGGCGACGATAGGTATTATTGACGGCAACAGTAGACCAGTATTGATGACAAGTGGCAAACAGCAGAGAAAAGCAACCATAGCACTTCACGATGACACAGGACAGGAATCTGGAACAGACGAGGGATCTTGGGATGGCGATGACGACGATAGGTTTATTGATCCAGATGACCTCGGGGCTGAGGACGGTGAGGACAGAGGTGATTTACTTGACGAGTTGGATTATGCGCCCCTTTGACTTGTGATACACGCGAAAAAGAAAGTCATGAATATCTGGGCGGAATGTTTCCCATCCCTAAAACAGGCCTTCCATCTAGGTGAGGCCGTCTTATGGCTACACCCTCCCGGCCTGATTCAGCTCAGGCATTCCGGTTTCGAATGGAGTGAACTGGAGATGGTGTGGGATGTGCTTCTGGGATCCCCGGCGCGCGCGTCGCCCGAAACATCCTGGTACAAGCACTCCAGCGTTGGCTTCGAATGAACTAGAGACGGTACTGAAGCGTGAGAGGGGAGAGGTGCAACGAGAATGGCCACTAGGGGCTTGCAGCGACGGGTCCCCCGCCCCCTCGAGCGCTACAGCGTCTGGACCTGTCAAGGGGTCTAGTGGCCGGGCGCCACCAGACTGGAACCGTGAATGAGACTGAGACACCTGAATGTCTCCAGTTCAGCGATGGCGAGAGCAGAGTGGGACCGTACGTACCTTGAGAACGACAACGAGGTTGCAGTAAAGGTCGT *       NM:i:882        ms:i:205        AS:i:176        nn:i:0

The scaffold_131 length is 71749 bp.

**Comment by ydLiu-HIT** [comment]
Hi, 
I am confused! I just re-run this read, but I got,

76:1172|992467c3-d94a-4021-a45c-a0ccb6f26176   0       scaffold_132    1       60      893S210M        *       0       0       CTGACTGGAACTACCATCAGCGCATGTAGAAATGCAACATCATCTGTTCAAGCACAACACTAAAAAATGCTGGGTGTTGATAAGGACGCAATAAGCTGAGTTCAGGGGATGGGGCAAACCTGCCACGCTTCCCACGATGCGGCAGAAGGCACTGCTGAGGACCGTGATGCGCTCGGCCTTCCCAGACCCCAGCACAGAAGTCTAGTGGTAGTAACGTCAGGGCATACGAAGCAGGGAGCTTGGAAGAGGATGAAGAGGCTGGATGCTGGAGGATGAGGATGACAATGAAGAAGGCGATGATGGCGAAAACGAAGACGGCAATGCTTGAAAGCGGCAATGAGATGAAACGAAAGATGATGAGATGAGAAGTAGGCGACGATAGGTATTATTGACGGCAACAGTAGACCAGTATTGATGACAAGTGGCAAACAGCAGAGAAAAGCAACCATAGCACTTCACGATGACACAGGACAGGAATCTGGAACAGACGAGGGATCTTGGGATGGCGATGACGACGATAGGTTTATTGATCCAGATGACCTCGGGGCTGAGGACGGTGAGGACAGAGGTGATTTACTTGACGAGTTGGATTATGCGCCCCTTTGACTTGTGATACACGCGAAAAAGAAAGTCATGAATATCTGGGCGGAATGTTTCCCATCCCTAAAACAGGCCTTCCATCTAGGTGAGGCCGTCTTATGGCTACACCCTCCCGGCCTGATTCAGCTCAGGCATTCCGGTTTCGAATGGAGTGAACTGGAGATGGTGTGGGATGTGCTTCTGGGATCCCCGGCGCGCGCGTCGCCCGAAACATCCTGGTACAAGCACTCCAGCGTTGGCTTCGAATGAACTAGAGACGGTACTGAAGCGTGAGAGGGGAGAGGTGCAACGAGAATGGCCACTAGGGGCTTGCAGCGACGGGTCCCCCGCCCCCTCGAGCGCTACAGCGTCTGGACCTGTCAAGGGGTCTAGTGGCCGGGCGCCACCAGACTGGAACCGTGAATGAGACTGAGACACCTGAATGTCTCCAGTTCAGCGATGGCGAGAGCAGAGTGGGACCGTACGTACCTTGAGAACGACAACGAGGTTGCAGTAAAGGTCGT *       NM:i:0  ms:i:210        AS:i:210        nn:i:0

The result was quite different from yours.  I have attached the source code, bother to you try again.

Best.

[deSALT-v1.5.3.zip](https://github.com/ydLiu-HIT/deSALT/files/4238714/deSALT-v1.5.3.zip)

**Comment by HegedusB** [comment]
Thanks Liu,
I think the three "deSALT-v1.5.3.zip" files are different. The last version, you linked is working. Do not cause the same error in tama but cause something else. I have to consult with the tama developer first to figure out the reason of the error.

Botond
